name: My First WorkFlow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.4.0

      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
          echo "My secret is ${{ secrets.MY_SECRET }}."

      - run: tree
