name: My First WorkFlow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.4.0

      - run: |
          echo "Hello world from ${{ github.actor }}."
          echo "Current branch is '${{ github.ref }}'."

      - run: tree
